language: php

php:
  - 7.2.5

cache:
  directories:
    - node_modules
    - vendor

before_script:
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction
  - php mama --version

script:
  - php mama test
