version: '3.8'

services:

  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    image: msllp/test:latest
    container_name: webserver
    ports:
      - "80:80"
      - "90:90"
      - "443:443"
    volumes:
      - ../o3 mainframe:/app/backend
      - ../o3 website:/app/frontend
    networks:
      - app-network



#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
