version: '3.7'
services:
  #WebServer


  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    image: msllp/test:latest
    container_name: webserver
    ports:
      - "80:80"
      - "90:90"
      - "443:443"
    volumes:
      - ./bootstrap:/app/bootstrap
      - ./vendor/msllp:/app/vendor/msllp
    networks:
      - app-network



#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
